### ISSUE TITLE
对于 1.5 的疑问

### ISSUE THREAD

**Issue by haoyuns** [boltomli/tidy-text-mining-zh#1]
在1.5 用 tidy 处理中文大作这一节的开始：
``` R
cutter <- worker(bylines = TRUE, stop_word = "data/stop_word_zh.utf8")
tidy_mingqingxiaoshuo <- mingqingxiaoshuo %>%
  mutate(text = sapply(segment(text, cutter), function(x){paste(x, collapse = " ")})) %>%
  unnest_tokens(word, text)
tidy_mingqingxiaoshuo
```
用 jieba 分词后再用 unnest_tokens 是会覆盖结巴的分词结果的，不知道这步是不是写错了

**Comment by boltomli** [comment]
`function(x){paste(x, collapse = " ")}` 这里把分词结果加了空格，后面就是简单按空格分词了

**Comment by haoyuns** [comment]
> `function(x){paste(x, collapse = " ")}` 这里把分词结果加了空格，后面就是简单按空格分词了

嗯嗯，我知道这步是在用jieba分词并整理结果格式，但是它后面的 `unnest_tokens(word, text)` 是会重新分一遍词的，即会覆盖jieba的结果，可以对比不加这句后的具体词语，应该是不一样的

**Comment by haoyuns** [comment]
> `function(x){paste(x, collapse = " ")}` 这里把分词结果加了空格，后面就是简单按空格分词了

嗯嗯，我知道这句是在用jieba分词并调整结果格式，但是它的后一句`unnest_tokens(word, text)`是会用tidytext重新分词的。我用你的数据包重跑了一遍，没有后半句的结果在`tidy_mingqingxiaoshuo2`，截图里可以看出会把jieba分词后的结果再tokenize一遍。

<img width="847" alt="r" src="https://user-images.githubusercontent.com/3357004/110734033-f5127c00-8261-11eb-8c82-cd3466de4b1a.png">

不过可能你本意就是要再分一遍？

**Comment by boltomli** [comment]
哇，这是个好发现啊。

当时版本的 **tidytext** 是不会对中文做改变的。看起来，现在也许可以试试不用 **jiebaR** 了？

我当时做这个 repo 在中文上重复原作者操作的主要出发点就是

1. 没有中文分词（没法直接应用原作的方法）
1. 没法输出含中文的图（图例、文字等）。

**Comment by haoyuns** [comment]
> 哇，这是个好发现啊。
> 
> 当时版本的 **tidytext** 是不会对中文做改变的。看起来，现在也许可以试试不用 **jiebaR** 了？
> 
> 我当时做这个 repo 在中文上重复原作者操作的主要出发点就是
> 
> 1. 没有中文分词（没法直接应用原作的方法）
> 2. 没法输出含中文的图（图例、文字等）。

我用别的文本试过，感觉还是 jiebaR 比较靠谱......
